version: "3"

tasks:
  default:
    silent: true
    cmd: "{{.TASK_EXE}} --list"

  check:
    desc: "Check code formatting and linting"
    cmds:
      - uv run ruff format --check
      - uv run ruff check

  format:
    desc: "Format files"
    cmds:
      - uv run ruff format
      - uv run ruff check --fix-only

  test:
    desc: "Run tests"
    cmd: uv run pytest tests/test_main.py
    
  # Can be deleted, for demonstration purposes only
  hello:
    desc: "Run the hello world script"
    cmd: uv run python -m app.main

