name: ${COMPOSE_PROJECT_NAME}

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - path: .env.local
        required: false
    container_name: devcontainer-${COMPOSE_DEVCONTAINER_PREFIX}
    # network_mode: host
    volumes:
      - "..:/workspace/${WORKSPACE_FOLDER_NAME}:rw,cached"
      # - "cache-uv:/home/vscode/.cache/uv"
    command: sleep infinity
    # command: ["sh", "-c", "chown -R vscode:vscode /home/vscode/.cache && exec sleep infinity"]

# volumes:
#   cache-uv:
